### ISSUE TITLE
plans of update postcss to v5?

### ISSUE THREAD

**Issue by tinchoz49** [css-modules/css-modules-loader-core#21]
Hi guys!
First, great library and i really like the idea behind of css-module :+1: . This is more like a question or feature...do you have plans of update postcss to v5?

Thanks!

**Comment by geelen** [comment]
Hadn't realised there'd been an update. I'll look into if there's any breaking changes but I reckon we want to keep up with the latest postcss as a rule.

**Comment by tinchoz49** [comment]
great @geelen, thanks! do i close the issue or wait until postcss was updated?

**Comment by Granze** [comment]
I'm trying to implement [css-modulesify](https://github.com/css-modules/css-modulesify) in my project (running postCss v5) but it doesn't work with the v4 dependency. Any news regarding the update?

Thanks!

**Comment by MeoMix** [comment]
:+1: Please upgrade!

**Comment by ryanseddon** [comment]
Ya'll should hookup greenkeeper.io

**Comment by douglasduteil** [comment]
+1
I'm going to investigate guys. I keep you paged.

**Comment by chentsulin** [comment]
+1
@geelen Anything block this?

```
$ npm i --save postcss@latest postcss-modules-extract-imports@latest postcss-modules-local-by-default@latest postcss-modules-scope@latest
postcss-modules-extract-imports@1.0.0-beta2 node_modules/postcss-modules-extract-imports

$ npm test
```

All tests is passing.

**Comment by douglasduteil** [comment]
@tinchoz49 @chentsulin @geelen isn't it done now ? Can this issue be closed ?

**Comment by chentsulin** [comment]
:+1: This can be closed now. Upgrade `css-loader` to 0.21.0 no warning shown any more.

**Comment by douglasduteil** [comment]
Great :)
